# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [5]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [6]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [7]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [8]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [11]:
# Your code here :
from sklearn.model_selection import train_test_split
seed = 1

X = data.drop('MEDV', axis=1)  # Todas las columnas (X) EXCEPTO Y
y = data['MEDV']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=seed
)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [12]:
# Your code here :
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()

model_linear.fit(X_train, y_train)


LinearRegression()

## 3. Calculate and print R-squared for both the training and the testing set.

In [16]:
# Your code here :
from sklearn.metrics import mean_squared_error
import numpy as np

hw_test = model_linear.predict(X_test)
hw_train = model_linear.predict(X_train)

r2_test = model_linear.score(X_test, y_test)

r2_train = model_linear.score(X_train, y_train)

print(f"VALORES TEST")
print(f"R² (Coeficiente de Determinación): {r2_test:.4f}")
print(f"########################################")
print(f"VALORES TRAIN")
print(f"R² (Coeficiente de Determinación): {r2_train:.4f}")

VALORES TEST
R² (Coeficiente de Determinación): 0.7634
########################################
VALORES TRAIN
R² (Coeficiente de Determinación): 0.7294


## 4. Calculate and print mean squared error for both the training and the testing set.

In [17]:
# Your code here :
mse_test = mean_squared_error(y_test, hw_test)

mse_train = mean_squared_error(y_train, hw_train)

print(f"VALORES TEST")
print(f"MSE (Error Cuadrático Medio):     {mse_test:.4f}")
print(f"RMSE (Raíz del MSE):               {np.sqrt(mse_test):.4f}")
print(f"########################################")
print(f"VALORES TRAIN")
print(f"MSE (Error Cuadrático Medio):     {mse_train:.4f}")
print(f"RMSE (Raíz del MSE):               {np.sqrt(mse_train):.4f}")

VALORES TEST
MSE (Error Cuadrático Medio):     23.3808
RMSE (Raíz del MSE):               4.8354
########################################
VALORES TRAIN
MSE (Error Cuadrático Medio):     21.8628
RMSE (Raíz del MSE):               4.6758


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [21]:
# Your code here :
actual = y.mean()

mae = actual - mse_test

print(f"MAE = {mae}")


MAE = -0.8480301561594672


## Classification Model Evaluation

In [22]:
from sklearn.datasets import load_iris
data = load_iris()

In [23]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [24]:
column_names = data.feature_names

In [25]:
df = pd.DataFrame(data['data'],columns=column_names)

In [26]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [27]:
target = pd.DataFrame(data.target)

In [28]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [29]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [30]:
# Your code here :
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='species')

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                   test_size=0.2,
                                   random_state=seed,
                                   stratify=y)


## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [32]:
# Your code here :
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()

model.fit(X_train, y_train)


y_pred_test = model.predict(X_test)
y_pred_train = model.predict(X_train)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [37]:
# Your code here :
accuracy_test = accuracy_score(y_test, y_pred_test)

accuracy_train = accuracy_score(y_train, y_pred_train)

print(f"Accuracy (Exactitud) test: {accuracy_test*100:.2f}%")
print(f"Accuracy (Exactitud) train: {accuracy_train*100:.2f}%")

Accuracy (Exactitud) test: 96.67%
Accuracy (Exactitud) train: 96.67%


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [38]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score

# Balanced accuracy para test y train
balanced_accuracy_test = balanced_accuracy_score(y_test, y_pred_test)
balanced_accuracy_train = balanced_accuracy_score(y_train, y_pred_train)

print(f"Balanced Accuracy test: {balanced_accuracy_test*100:.2f}%")
print(f"Balanced Accuracy train: {balanced_accuracy_train*100:.2f}%")

Balanced Accuracy test: 96.67%
Balanced Accuracy train: 96.67%


## 10. Calculate and print the precision score for both the training and the testing set.

In [40]:
# Your code here :
from sklearn.metrics import precision_score

# Precision para test y train
precision_test = precision_score(y_test, y_pred_test, average='macro')
precision_train = precision_score(y_train, y_pred_train, average='macro')
print(f"Precision test: {precision_test*100:.2f}%")
print(f"Precision train: {precision_train*100:.2f}%")

Precision test: 96.97%
Precision train: 96.67%


## 11. Calculate and print the recall score for both the training and the testing set.

In [42]:
# Your code here :

from sklearn.metrics import recall_score

# Recall para test y train
recall_test = recall_score(y_test, y_pred_test, average='macro')
recall_train = recall_score(y_train, y_pred_train, average='macro')

print(f"Recall test: {recall_test*100:.2f}%")
print(f"Recall train: {recall_train*100:.2f}%")

Recall test: 96.67%
Recall train: 96.67%


## 12. Calculate and print the F1 score for both the training and the testing set.

In [43]:
# Your code here :
from sklearn.metrics import f1_score

# F1 score para test y train
f1_test = f1_score(y_test, y_pred_test, average='macro')
f1_train = f1_score(y_train, y_pred_train, average='macro')
print(f"F1 Score test: {f1_test*100:.2f}%")
print(f"F1 Score train: {f1_train*100:.2f}%")

F1 Score test: 96.66%
F1 Score train: 96.67%


## 13. Generate confusion matrices for both the training and the testing set.

In [44]:
# Your code here :
from sklearn.metrics import confusion_matrix

# Matriz de confusión para el conjunto de test
cm_test = confusion_matrix(y_test, y_pred_test)
print("Confusion Matrix (Test):")
print(cm_test)

# Matriz de confusión para el conjunto de train
cm_train = confusion_matrix(y_train, y_pred_train)
print("\nConfusion Matrix (Train):")
print(cm_train)

Confusion Matrix (Test):
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]

Confusion Matrix (Train):
[[40  0  0]
 [ 0 38  2]
 [ 0  2 38]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !